RATEST-200 E2E Location management workflow test
openmrs/openmrs-contrib-qaframework pull request #331
Opened 2022-01-25 17:43 UTC by Ndacyayisenga-droid

Ticked id RATEST-200
Ticket url https://issues.openmrs.org/browse/RATEST-200

2022-01-26 06:43 UTC, Ndacyayisenga-droid commented
@kdaud @sherrif10 I dont know for what reason I cant access cucumber reports

2022-01-26 06:57 UTC, kdaud commented on .github/workflows/refapp-2x-location-management.yml
> +          npm run refapp2LocationManagement
```suggestion
 cd qaframework-bdd-tests
 npm run refapp2LocationManagement
```

2022-01-26 06:59 UTC, kdaud commented
> I dont know for what reason I cant access cucumber reports

Its because the command is running against the parent module not within  qaframework-bdd-tests module.

2022-01-26 07:41 UTC, kdaud commented on .github/workflows/refapp-2x-location-management.yml
> + npm run refapp2LocationManagement
worth looking into the indention

2022-01-28 11:12 UTC, mherman22 requested changes

2022-01-28 11:12 UTC, mherman22 commented on qaframework-bdd-tests/src/test/resources/features/refapp-2.x/05-location/locations.feature
> +    And a user clicks on Manage Location Attribute Types
don't you agree with me that when `a user clicks on Manage Location Attribute Types`, then `the system loads the manage location attribute types page`?

2022-01-28 11:12 UTC, mherman22 commented on qaframework-bdd-tests/src/test/resources/features/refapp-2.x/05-location/locations.feature
> +    And a user clicks on add new location attribute type
```suggestion
    And a user clicks on add new location attribute type button
```

2022-01-28 11:12 UTC, mherman22 commented on qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/LocationManagementSteps.java
> +    public void loadsConfigureMetaData(){
```suggestion
    public void loadsConfigureMetaData() {
```
please do the same for all the other methods

2022-01-28 11:39 UTC, mherman22 requested changes

2022-01-28 11:39 UTC, mherman22 commented on qaframework-bdd-tests/src/test/resources/features/refapp-2.x/05-location/locations.feature
> +    And a user fills add new location form
what happens when the user fills the add new location form?

2022-02-23 04:23 UTC, mherman22 commented on qaframework-bdd-tests/src/test/resources/features/refapp-2.x/05-location/locations.feature
> +    And a user fills add new location form
@Ndacyayisenga-droid please find time and address these questions

2022-02-23 08:54 UTC, sherrif10 commented
Hello my dear @Ndacyayisenga-droid  can we give support for this ticket to make you move.

2022-02-27 13:23 UTC, closed without merging