RATEST-302:Add an Identifier for a patient
openmrs/openmrs-contrib-qaframework pull request #353
Opened 2022-02-09 08:15 UTC by gracebish

Jira Issue Number and Title
RATEST-302:Test case: Add an identifier for a patient
Description of changes
Add an identifier for a patient
Issue worked on
https://issues.openmrs.org/browse/RATEST-302

2022-02-09 09:39 UTC, Irenyak1 commented on qaframework-bdd-tests/package.json
> +    "refapp2AddNewIdentifier": "mvn test -Dcucumber.filter.tags='@selenium and @addNewIdentifier'",
@gracebish could you move this script to where the refapp2 scripts are.

2022-02-09 09:40 UTC, Irenyak1 commented on qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/AdministrationPage.java
> +
@gracebish you only need one empty line here. You could delete the others.

2022-02-09 09:44 UTC, Irenyak1 commented on qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/PatientFormPage.java
> +
@gracebish  try to have just an empty line at the end of the file. These lines are considered as having code/spaces.

2022-02-14 16:52 UTC, kdaud commented
@gracebish update your branch with changes from master

2022-02-21 02:16 UTC, sherrif10 commented
Hello @gracebish  you could resolve conflicting files.

2022-02-21 05:13 UTC, gracebish commented
@sherrif10 Not yet. Yesterday i had a sync with @kdaud to help me see whether the tests would run successfully on my windows os and we did not succeed. He slept over it and we are trying to find a solution.

2022-02-21 05:18 UTC, sherrif10 commented
Sorry about that , Have never tried this on a windows machine before. Is it possible for you to try linux environments it would save you lots of time.

2022-03-14 22:28 UTC, jwnasambu requested changes
Kindly ensure `given`  spec is on the same line as other specification in the background section.

```
Background: 
  Given a user clicks on system administration link on the home page
    Then the system loads administration page
    And a user clicks on the manage Patients link on the administration page
    Then the system loads patient page
```

2022-03-14 22:47 UTC, jwnasambu reviewed
Kindly ensure `given`  spec is on the same line as other specification in the background section.

```
Background: 
    Given a user clicks on system administration link on the home page
    Then the system loads administration page
    And a user clicks on the manage Patients link on the administration page
    Then the system loads patient page
```

2022-03-16 06:53 UTC, gracebish commented
I am still checking out why the IDE presents something different from the commit. Please do not mind this commit.

2022-04-11 02:53 UTC, sherrif10 commented
Hello @gracebish  Are you still working on this. Any progress.

2022-04-11 18:17 UTC, jwnasambu commented
@sherrif10 Her laptop broke down and she is trying to fix it .

2022-04-15 16:51 UTC, pasindur99 requested changes
@gracebish Can you add the status badge of this workflow to the QA Dashboard?

2022-04-28 08:03 UTC, sherrif10 commented
Are you still interested in working on this @gracebish  . You could start with resolving merge conflicts.

2023-09-24 17:39 UTC, sherrif10 commented
Closing this Pull request.

2023-09-24 17:39 UTC, closed without merging