O3-1056: Move Patient Registration E2E test to the dockerized environment
openmrs/openmrs-contrib-qaframework pull request #358
Opened 2022-02-10 13:25 UTC by kumuditha-udayanga

### Purpose
The purpose of this PR is to fix [O3-1056](https://issues.openmrs.org/browse/O3-1056).

### Approach
- Run 3. x patient registration E2E test in a dockerized environment.

Note: The test fails due to a bug in the patient registration application, it is been fixed in the production server([O3-867](https://issues.openmrs.org/browse/O3-867)). The current docker image doesn't include that change.

2022-02-10 15:19 UTC, jayasanka-sack requested changes
Could you please add the `dockerize-3.x` branch to the `on` section?

2022-02-10 15:29 UTC, jayasanka-sack requested changes

2022-02-10 15:29 UTC, jayasanka-sack commented on .github/workflows/refapp-3x-patient-registration.yml
> +    branches: [ dockerize-3.x ]
Keep master too.
```suggestion
    branches:
       - master
       - dockerize-3.x
```
or,
```suggestion
    branches: [ master, dockerize-3.x ]
```

2022-02-10 15:29 UTC, jayasanka-sack commented on .github/workflows/refapp-3x-patient-registration.yml
> +    branches: [ dockerize-3.x ]
applied to the pull request section as well

2022-02-10 15:50 UTC, jayasanka-sack commented
@kumuditha-udayanga It seems there's something wrong with the action. It ran for 20 mins and I cancelled the workflow. 
Could you please check it?

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/33048395/153444067-2fd0ebb2-3a89-4712-a96d-11ae99e32750.png">

2022-02-14 16:08 UTC, kumuditha-udayanga commented
Sure

2022-02-15 15:31 UTC, kumuditha-udayanga commented
Sure @jayasanka-sack, I'll look into it.

2022-02-28 05:18 UTC, sherrif10 commented
Hey @kumuditha-udayanga  Still looking into this.

2022-04-15 15:37 UTC, pasindur99 requested changes

2022-04-15 15:37 UTC, pasindur99 commented on .github/workflows/refapp-3x-patient-registration.yml
> +          repository: ${{github.repository}}
You do not need to add this section to the workflow, because `repository: ${{github.repository}}` contains a default value.

2022-04-27 18:08 UTC, jayasanka-sack commented
The setup isn't viable to address current challenges. We should work on a different approach. Therefore, closing the PR.

Thanks @kumuditha-udayanga !

2022-04-27 18:08 UTC, closed without merging