RATEST-344: Fix the failing RefApp 2.x Clinical Visit Test
openmrs/openmrs-contrib-qaframework pull request #476
Opened 2023-02-19 02:56 UTC by chirandevinda

2023-02-19 15:35 UTC, Piumal1999 requested changes
The test is passing. But we can improve this test as mentioned [here](https://talk.openmrs.org/t/fixing-random-failures-in-qa-framework-e2e-tests/38579/14?u=piumal1999)

2023-02-19 15:35 UTC, Piumal1999 commented on qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
> +    	assertEquals(DIAGNOSIS_PRIMARY, visitNotePage.savedPrimaryDiagnosis());
@chirandevinda fix the identation here

2023-02-21 05:30 UTC, mherman22 commented
@chirandevinda can we add a clear description to this pull request? Refer to https://wiki.openmrs.org/display/docs/Pull+Request+Tips

2023-02-25 04:16 UTC, chirandevinda commented
I will make a new PR with the description

2023-02-25 04:27 UTC, chirandevinda commented
**Summary**
The RefApp 2.x Clinical Visit Test workflow is currently failing. Specifically, it fails when attempting to save a visit note in the Complete visit note user story.
**Screenshots**
Tested with GitHub actions:
![image](https://user-images.githubusercontent.com/73557402/221336988-79646834-3402-4251-b734-a79d8adfbe4f.png)
**Related Issue**
https://issues.openmrs.org/browse/RATEST-344

2023-02-25 09:29 UTC, Piumal1999 commented on qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
>  	}
```suggestion
	}

```
Add an empty line here

2023-02-25 10:51 UTC, Piumal1999 approved these changes
Looks good to me. Good job! @chirandevinda
Thank you

2023-02-28 14:56 UTC, merged