Creating a pull request template
openmrs/openmrs-contrib-qaframework pull request #477
Opened 2023-02-20 09:36 UTC by dilankavishka

I created a pull request template for (https://github.com/openmrs/openmrs-contrib-qaframework) repository.

2023-02-20 09:38 UTC, dilankavishka commented
@Piumal1999 Can you review this please?

2023-02-20 19:19 UTC, mherman22 requested changes

2023-02-20 19:19 UTC, mherman22 commented on .github/pull_request_template.md
> +[ ] I have tested the changes locally and verified that they work as intended.
```suggestion
- [ ] I have tested the changes locally and verified that they work as intended.
```

2023-02-20 19:19 UTC, mherman22 commented on .github/pull_request_template.md
> +[ ] I have tested the changes locally and verified that they work as intended.
add that dashes (`-`) at the beginning of these lines. reference -> https://www.markdownguide.org/extended-syntax/, look for a title called **Task Lists**

2023-02-20 19:19 UTC, mherman22 commented on .github/pull_request_template.md
> +[ ] I have updated the relevant documentation and/or tests to reflect the changes.
do the same here!

2023-02-20 19:19 UTC, mherman22 commented on .github/pull_request_template.md
> +[ ] I have added comments to my code where necessary to help others understand my changes.
same here!

2023-02-20 19:19 UTC, mherman22 commented on .github/pull_request_template.md
> +[ ] I have read and agree to the Contributing Guidelines of this project.
same here!

2023-02-20 19:52 UTC, Piumal1999 commented
I think we can reuse[ this template](https://github.com/openmrs/openmrs-esm-patient-management/blob/main/.github/pull_request_template.md) by just updating the checklist. It also contains clear and concise [instructions as comments](https://github.com/openmrs/openmrs-esm-patient-management/blob/main/.github/pull_request_template.md?plain=1).

And @dilankavishka make sure that you update **this pull request's** description according to the same structure.

2023-02-21 05:18 UTC, dilankavishka commented on .github/pull_request_template.md
> +[ ] I have read and agree to the Contributing Guidelines of this project.
Thank you @mherman22

2023-02-21 05:19 UTC, dilankavishka commented
sure! @Piumal1999

2023-02-22 17:16 UTC, dilankavishka commented
@Piumal1999  I'm done with the changes. can you please check that?

2023-02-22 18:12 UTC, Piumal1999 approved these changes
Looks good! Thank you @dilankavishka 

cc: @jayasanka-sack

2023-02-22 19:14 UTC, mherman22 approved these changes

2023-02-28 14:54 UTC, merged