RATEST-62 Write allergies page
openmrs/openmrs-contrib-qaframework pull request #6
Opened 2020-10-09 17:18 UTC by achilep

Issue I on: https://issues.openmrs.org/browse/RATEST-63

2020-10-12 07:33 UTC, HerbertYiga commented
Thanks @achilep ,we can also improve our description by using some thing like (RATEST-62: Write allergies page

2020-10-12 07:34 UTC, HerbertYiga commented
cc @kaweesi

2020-10-13 21:33 UTC, kaweesi commented on src/test/java/org/openmrs/contrib/qaframework/page/AllergiesPage.java
> +
please add more of the actions expected off this page such as edit, delete, add new etc

2020-10-13 21:34 UTC, kaweesi requested changes
looks very promising, please check my comment above

2020-10-14 16:06 UTC, achilep commented
hello, @kaweesi please can you review it again? thanks

2021-02-17 11:12 UTC, sherrif10 commented
This should also be closed due to alergy page[ here](url)https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/src/test/java/org/openmrs/contrib/qaframework/page/AllergiesPage.java

2021-02-18 15:09 UTC, kaweesi commented
@achilep  are you still interested in completing this PR? please update it basing on the existing page file in master

2021-02-18 18:05 UTC, achilep commented
yes, thanks @kaweesi, I will update the PR.

2021-02-18 22:37 UTC, achilep commented on src/test/java/org/openmrs/contrib/qaframework/automation/AllergiesSteps.java
> +	}
I wrote the step definition, the page, and the feature @kaweesi

2021-02-19 08:36 UTC, kaweesi commented on src/test/java/org/openmrs/contrib/qaframework/automation/AllergiesSteps.java
> +	}
add a space here

2021-02-19 08:37 UTC, kaweesi commented on src/test/java/org/openmrs/contrib/qaframework/page/AllergiesPage.java
> +	public static final By CHOOSEDRUG = By.id("allergen-162299");
these elements are data dependent, use references that aren't tied onto ids since they never exist on another instance

2021-02-19 08:40 UTC, kaweesi commented on src/test/resources/features/11-allergy/allergies.feature
> +  Scenario: Add New Allergy
then this should be loading the page. add new allergy should rather check if the system does add the allergy

2021-02-19 08:40 UTC, kaweesi reviewed
thanks @achilep  please check my most recent comments

2021-02-27 12:24 UTC, achilep commented
@kaweesi  I'm a little confused with your refactoring at this level: https://github.com/openmrs/openmrs-contrib-qaframework/commit/bc1be006c21e925ee427addbba98c03eb626562a#r47628678

2021-03-11 14:44 UTC, kaweesi commented on src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java
> +		dashboardPage.clickOnConditionsWidgetLink();
this is nice @achilep could you split these changes into another PR to make this PR more readable

2021-03-11 14:47 UTC, kaweesi commented
@achilep please check my comments, ensure this PR is updated with master and not showing changes in master. Resolve the conflicts and then i can re-review

2021-03-24 19:04 UTC, achilep commented
@kaweesi  The allergy page is on this PR  https://github.com/openmrs/openmrs-distro-referenceapplication/pull/346

2021-08-15 03:34 UTC, kdaud commented
@achilep are you still working on this PR ?

2021-08-15 03:36 UTC, sherrif10 commented
Did you see merge conflicts

2021-09-16 20:32 UTC, closed without merging